### ISSUE TITLE
Tests not working or running

### ISSUE THREAD

**Issue by rfay** [iamntz/ddev-rename-project#2]
It looks like you gave up on tests for this, and it doesn't have automated tests.

Are you still interested in maintaining this? 

If so, please consider
* Updating the tests.yml file to https://github.com/ddev/ddev-addon-template/blob/main/.github/workflows/tests.yml so that it doesn't time out any more.
* Getting the tests (or the add-on) working again.

If not, please consider removing the `ddev-get` label and probably update the README to say that it's no longer maintained. Or find another maintainer?

Thanks!
-Randy

**Comment by iamntz** [comment]
fixed with 928d22da7680cba8beb1220acb0fdde25e9986c1

**Comment by rfay** [comment]
Thanks!
